name : Addition

on:
  push:
    branches:
      - Main
    paths:
      - "addition.py"

jobs:
  Addition-ci:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        A: [1,5,200]
        B: [9,28,198]  

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Run Addition with matrix
        run: python addition.py
        env:
          A: ${{matrix.A}}
          B: ${{matrix.B}}

      # - name: Run Addition with arguments
      #   run: python3 addition.py 90 29

      # - name: Run Addition Script
      #   run : python3 addition.py